# Generated by Django 5.1.3 on 2024-11-24 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=20, unique=True)),
                ('contracted', models.CharField(max_length=255)),
                ('contract_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publication_date', models.DateField()),
                ('signing_date', models.DateField()),
                ('contracting_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio_invest.municipality')),
            ],
        ),
    ]
