# Generated by Django 5.1.3 on 2024-11-24 11:50

from django.db import migrations


def add_municipalities(apps, schema_editor):
    # Get the Municipality model from the historical version
    Municipality = apps.get_model('municipio_invest', 'Municipality')

    # Entries to add
    municipalities = [
        {'name': 'Município de Baião', '_id': 41},
        {'name': 'Município de Penafiel', '_id': 2910},
        {'name': 'Município de Amarante', '_id': 1923},
        {'name': 'Município de Paços de Ferreira', '_id': 16351},
        {'name': 'Município de Marco de Canaveses', '_id': 2872},
        {'name': 'Município de Lousada', '_id': 1069},
        {'name': 'Município de Cinfães', '_id': 2533},
        {'name': 'Município de Castelo de Paiva', '_id': 153},
        {'name': 'Município de Celorico de Basto', '_id': 1150},
        {'name': 'Câmara Municipal de Resende', '_id': 234},
        {'name': 'Câmara Municipal de Felgueiras', '_id': 1445},

    ]

    # Add entries to the database
    for data in municipalities:
        Municipality.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('municipio_invest', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_municipalities),
    ]
