# Generated by Django 5.1.3 on 2024-11-24 14:03

from django.db import migrations

def populate_nuts_regions(apps, schema_editor):
    NUTSIII = apps.get_model('municipio_invest', 'NUTSIII')
    
    nuts_regions = [
        "Alto Minho",
        "Cávado",
        "Ave",
        "Área Metropolitana do Porto",
        "Alto Tâmega e Barroso",
        "Tâmega e Sousa",
        "Douro",
        "Terras de Trás-os-Montes",
        "Região de Aveiro",
        "Região de Coimbra",
        "Região de Leiria",
        "Viseu Dão Lafões",
        "Beira Baixa",
        "Beiras e Serra da Estrela",
        "Grande Lisboa",
        "Médio Tejo",
        "Lezíria do Tejo",
        "Oeste",
        "Península de Setúbal",
        "Alentejo Litoral",
        "Baixo Alentejo",
        "Alto Alentejo",
        "Alentejo Central",
        "Algarve",
        "Região Autónoma dos Açores",
        "Região Autónoma da Madeira"
    ]
    
    # Adicionar as regiões NUTS III ao banco de dados
    for region in nuts_regions:
        NUTSIII.objects.get_or_create(name=region)

class Migration(migrations.Migration):

    dependencies = [
        ('municipio_invest', '0003_district_nutsiii'),
    ]

    operations = [
        migrations.RunPython(populate_nuts_regions),

    ]
