# Generated by Django 5.1.3 on 2024-11-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio_invest', '0003_alter_municipality__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
