# Generated by Django 5.1.3 on 2024-11-24 14:09

from django.db import migrations

def populate_districts(apps, schema_editor):
    District = apps.get_model('municipio_invest', 'District')
    
    districts = [
        "Aveiro",
        "Beja",
        "Braga",
        "Bragança",
        "Castelo Branco",
        "Coimbra",
        "Évora",
        "Faro",
        "Guarda",
        "Leiria",
        "Lisboa",
        "Portalegre",
        "Porto",
        "Santarém",
        "Setúbal",
        "Viana do Castelo",
        "Vila Real",
        "Viseu",
        "Região Autónoma dos Açores",
        "Região Autónoma da Madeira"
    ]
    
    for district in districts:
        District.objects.get_or_create(name=district)

class Migration(migrations.Migration):

    dependencies = [
        ('municipio_invest', '0004_adicionar_nuts_III'),
    ]

    operations = [
        migrations.RunPython(populate_districts),
    ]
